[package]
name = "RSSFM2D"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
ndrustfft = "0.4.0"
ndarray-npy = "0.8.1"
num-complex = "0.4.6"
rayon = "1.10.0"
itertools = "0.13.0"
fstrings = "0.2.3"
plotters = "0.3.7"
plotly = "0.12.1"
colorous = "1.0.15"
colorgrad = "0.6"
